version: "3.8"

services:
  bot-1:
    container_name: linebot-webhook-bot1
    build: .
    environment:
      - TZ=Asia/Bangkok
    env_file: .env
    ports:
      - 19161:$NODE_PORT
    restart: on-failure

  bot-2:
    container_name: linebot-webhook-bot2
    build: .
    environment:
      - TZ=Asia/Bangkok
    env_file: .env
    ports:
      - 19162:$NODE_PORT
    restart: on-failure
  
  bot-3:
    container_name: linebot-webhook-bot3
    build: .
    environment:
      - TZ=Asia/Bangkok
    env_file: .env
    ports:
      - 19163:$NODE_PORT
    restart: on-failure
